### ISSUE TITLE
Plaid account: the `limit` field is described as a string, but the example shows a number

### ISSUE THREAD

**Issue by Saser** [lunch-money/api-docs#1]
On the page describing the Plaid account object (https://developers.lunchmoney.app/plaid-accounts/plaid-accounts-object), the `limit` field has a type of `string`. However, on the page describing the "Get all Plaid accounts" endpoint (https://developers.lunchmoney.app/plaid-accounts/get-all-plaid-accounts), the second object in the example response has a numeric value of `15000` for the `limit` field.

**Comment by Saser** [comment]
I assume that the correct type is `number`, so I whipped up a quick PR making the change: #2 :)

**Comment by lunchbag** [comment]
Thanks @Saser! Sorry for the late acknowledgement here!
